### ISSUE TITLE
Not working on server? 

### ISSUE THREAD

**Issue by D-Alessian** [Synthitic/GCYL-CEu#22]
I tried running it on a server with a pretty tame modlist, and it doesn't seem to be working. To me it looks like it's stuck trying to create the Deep Miner recipes. Tried on Forge and Cleanroom loaders, same results. Maybe it's on my side and I'm forgetting something but I tried for 3 hours and it really doesn't seem to be working. Disabling the gcyl-ceu.jar fixes it too, and it works on client.

Modlist (idk how to do the whole modlist.html thing) : 
![Screenshot_2024-06-15_155852](https://github.com/Synthitic/GCYL-CEu/assets/117815201/8815524a-b20f-488e-9582-cfc76765b113)

Logs : 
[logs.zip](https://github.com/user-attachments/files/15847911/logs.zip)

**Comment by Synthitic** [comment]
Does it work when running with this exact list on a client?

**Comment by Synthitic** [comment]
The issue is fixed, and will come with the next dev build jar posted in discord. Was a silly mistake, sorry it wasted your time.

**Comment by D-Alessian** [comment]
No worries, to be expected with the project being so new.
