### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by JennyDoll** [Synthitic/GCYL-CEu#3]
**SEE TITLE. THIS LIST IS NOT EXHAUSTIVE.** I abstained from specifying some items and fluids because they aren't used in other recipes, so they don't matter yet and can be fixed at a later date.

Solids and general metals: pikyonium, titan steel, staballoy, hastelloyx_78 (from now on no proper names for all materials), incoloy_813, jasper, americium 241 and 243, curium_250, uranium_generic, californium_252, sodium potassium alloy.
Fluids: cyclopentadiene, californium cyclopentadienide, hyper fuel I to III, liquid enriched helium, resin, superfluid helium, maleic anhydride, glyceryl, ortho-xylene, aniline, sodium toluenesulfonate (and the recipe it's used in also uses 0L of it, which feels wrong), boron free solution recipe takes "invalid item", outputs "invalid item", sea water to salt water does the same, same for sodium hydroxide solution.

EV to UIV battery hulls and batteries.
Infinite water covers.
Chemical dehydrators past UV, scrap makers past UHV.
Charged lepton trap crystals - required in UXV emitters.
Volcanus controller. Large mixer and large centrifuge controller (possibly phased out for GCYM multiblocks?). Fusion reactor controllers past UHV. Hyper reactor I controller (commented out, multiblock pattern still exists). Large naquadah reactor controller recipe is broken - doesn't have dense naquadria plates. Electric implosion compressor is missing osmium rings. Hyper reactor III controller - missing zeron-100 screws. Stellar containment casing - no trinium frame box.
UIV superconductor wires have a broken recipe. (pipeTinyFluid, TantalumHafniumSeaborgiumCarbide, 10) is missing. Same with LuV but different pipe and UV. 
**Mica insulator foils** - this is a big one! Aside from coils it's also used in supra-causal SMDs.
Industrial TNT and powder barrels - those two already exist in the main GTCEu.
All magneto resonatic circuits (commented out).
All sieves and yarns (some have recipes - that take "invalid item" that itself has no recipe and is missing textures; one has a recipe that works but requires another, now uncraftable yarn). 
Inductor takes a "Small Coil" which doesn't have a recipe and is missing textures.

Blood.

Optical assemblies have a missing component in form of (wireGtSingle, RutheniumTriniumAmericiumNeutronate). Optical computers have the same missing component. Same for optical mainframes. 

![](https://cdn.discordapp.com/attachments/785166124412174336/1246761454460338247/image.png?ex=665d9096&is=665c3f16&hm=b498e83946424cde2b82b1a5c6c092023e940559f1461298f9041289a3c72943&)

**Comment by Synthitic** [comment]
Hey, thanks for the work. One thing to note for reporting missing recipes, if you find recipes with "holes" like those 2 assline recipes in the screenshots, don't report them as it's very easy to fix. I have chosen not to fix them as the recipes may not be final and I do not know if I want to permanently generate those items yet, though it's very likely I will end up generating them anyways.
I will update the readme page about these kind of broken recipes.
